### ISSUE TITLE
MQTT event handlers

### ISSUE THREAD

**Issue by jkiv** [jkiv/b11y-twitch#6]
* [x] Unstateful callbacks?
* [x] Object/Stateful callbacks?

**Comment by jimf99** [comment]
Unstateful vs Object/Stateful callbacks.

Depends on the Application, Both are valid.

Also Message Queue Application Comparisons.

https://www.confluent.io/blog/kafka-fastest-messaging-system/

**Comment by jkiv** [comment]
Done with 20d36d6. Using class methods -- class can keep track of state.
